/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_LISTING_DURATION"
      | "MAX_PROFIT_SHARE"
      | "MIN_PRICE"
      | "cancelListing"
      | "cancelService"
      | "distributeProfitToInvestor"
      | "getAgentListings"
      | "getAgentServices"
      | "getMarketplaceStats"
      | "investInAgent"
      | "investmentCounter"
      | "investments"
      | "listItem"
      | "listingCounter"
      | "listings"
      | "marketplaceFeePercent"
      | "monToken"
      | "offerService"
      | "owner"
      | "pause"
      | "paused"
      | "purchaseItem"
      | "purchaseService"
      | "renounceOwnership"
      | "serviceCounter"
      | "services"
      | "setMarketplaceFee"
      | "totalFeesCollected"
      | "totalInvested"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "withdrawFees"
      | "withdrawInvestment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesWithdrawn"
      | "InvestmentMade"
      | "InvestmentWithdrawn"
      | "ItemListed"
      | "ItemPurchased"
      | "ListingCancelled"
      | "MarketplaceFeeUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "ProfitDistributed"
      | "ServiceCancelled"
      | "ServiceOffered"
      | "ServicePurchased"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_LISTING_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PROFIT_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_PRICE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelService",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeProfitToInvestor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentListings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentServices",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketplaceStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "investInAgent",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investmentCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "investments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listItem",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listingCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplaceFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "monToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "offerService",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseItem",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseService",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "serviceCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "services",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketplaceFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalInvested",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawInvestment",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_LISTING_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PROFIT_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_PRICE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeProfitToInvestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketplaceStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investInAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investmentCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listItem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listingCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplaceFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "monToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "offerService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serviceCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "services", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMarketplaceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalInvested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawInvestment",
    data: BytesLike
  ): Result;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentMadeEvent {
  export type InputTuple = [
    investmentId: BigNumberish,
    investor: AddressLike,
    agent: AddressLike,
    amount: BigNumberish,
    profitShare: BigNumberish
  ];
  export type OutputTuple = [
    investmentId: bigint,
    investor: string,
    agent: string,
    amount: bigint,
    profitShare: bigint
  ];
  export interface OutputObject {
    investmentId: bigint;
    investor: string;
    agent: string;
    amount: bigint;
    profitShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentWithdrawnEvent {
  export type InputTuple = [
    investmentId: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    investmentId: bigint,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    investmentId: bigint;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemListedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    seller: AddressLike,
    itemType: string,
    quantity: BigNumberish,
    price: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    seller: string,
    itemType: string,
    quantity: bigint,
    price: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    seller: string;
    itemType: string;
    quantity: bigint;
    price: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemPurchasedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    quantity: BigNumberish,
    totalPrice: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    buyer: string,
    seller: string,
    quantity: bigint,
    totalPrice: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    buyer: string;
    seller: string;
    quantity: bigint;
    totalPrice: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingCancelledEvent {
  export type InputTuple = [listingId: BigNumberish, seller: AddressLike];
  export type OutputTuple = [listingId: bigint, seller: string];
  export interface OutputObject {
    listingId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketplaceFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitDistributedEvent {
  export type InputTuple = [
    investmentId: BigNumberish,
    investor: AddressLike,
    profit: BigNumberish
  ];
  export type OutputTuple = [
    investmentId: bigint,
    investor: string,
    profit: bigint
  ];
  export interface OutputObject {
    investmentId: bigint;
    investor: string;
    profit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceCancelledEvent {
  export type InputTuple = [serviceId: BigNumberish, provider: AddressLike];
  export type OutputTuple = [serviceId: bigint, provider: string];
  export interface OutputObject {
    serviceId: bigint;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceOfferedEvent {
  export type InputTuple = [
    serviceId: BigNumberish,
    provider: AddressLike,
    serviceType: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    serviceId: bigint,
    provider: string,
    serviceType: string,
    price: bigint
  ];
  export interface OutputObject {
    serviceId: bigint;
    provider: string;
    serviceType: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServicePurchasedEvent {
  export type InputTuple = [
    serviceId: BigNumberish,
    buyer: AddressLike,
    provider: AddressLike,
    price: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    serviceId: bigint,
    buyer: string,
    provider: string,
    price: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    serviceId: bigint;
    buyer: string;
    provider: string;
    price: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): AgentMarketplace;
  waitForDeployment(): Promise<this>;

  interface: AgentMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_LISTING_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_PROFIT_SHARE: TypedContractMethod<[], [bigint], "view">;

  MIN_PRICE: TypedContractMethod<[], [bigint], "view">;

  cancelListing: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelService: TypedContractMethod<
    [serviceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeProfitToInvestor: TypedContractMethod<
    [investmentId: BigNumberish, profit: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAgentListings: TypedContractMethod<
    [agent: AddressLike],
    [bigint[]],
    "view"
  >;

  getAgentServices: TypedContractMethod<
    [agent: AddressLike],
    [bigint[]],
    "view"
  >;

  getMarketplaceStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalListings: bigint;
        totalServices: bigint;
        totalInvestments: bigint;
        feesCollected: bigint;
      }
    ],
    "view"
  >;

  investInAgent: TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish, profitShare: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  investmentCounter: TypedContractMethod<[], [bigint], "view">;

  investments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        investor: string;
        agent: string;
        amount: bigint;
        profitShare: bigint;
        timestamp: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  listItem: TypedContractMethod<
    [itemType: string, quantity: BigNumberish, pricePerUnit: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  listingCounter: TypedContractMethod<[], [bigint], "view">;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, boolean] & {
        seller: string;
        pricePerUnit: bigint;
        quantity: bigint;
        createdAt: bigint;
        itemType: string;
        active: boolean;
      }
    ],
    "view"
  >;

  marketplaceFeePercent: TypedContractMethod<[], [bigint], "view">;

  monToken: TypedContractMethod<[], [string], "view">;

  offerService: TypedContractMethod<
    [serviceType: string, pricePerAction: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  purchaseItem: TypedContractMethod<
    [listingId: BigNumberish, quantity: BigNumberish],
    [void],
    "nonpayable"
  >;

  purchaseService: TypedContractMethod<
    [serviceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  serviceCounter: TypedContractMethod<[], [bigint], "view">;

  services: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, string] & {
        provider: string;
        pricePerAction: bigint;
        completedJobs: bigint;
        active: boolean;
        serviceType: string;
      }
    ],
    "view"
  >;

  setMarketplaceFee: TypedContractMethod<
    [newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  totalInvested: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawFees: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawInvestment: TypedContractMethod<
    [investmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_LISTING_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PROFIT_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelService"
  ): TypedContractMethod<[serviceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeProfitToInvestor"
  ): TypedContractMethod<
    [investmentId: BigNumberish, profit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgentListings"
  ): TypedContractMethod<[agent: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getAgentServices"
  ): TypedContractMethod<[agent: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMarketplaceStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalListings: bigint;
        totalServices: bigint;
        totalInvestments: bigint;
        feesCollected: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "investInAgent"
  ): TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish, profitShare: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "investmentCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "investments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        investor: string;
        agent: string;
        amount: bigint;
        profitShare: bigint;
        timestamp: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "listItem"
  ): TypedContractMethod<
    [itemType: string, quantity: BigNumberish, pricePerUnit: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listingCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, boolean] & {
        seller: string;
        pricePerUnit: bigint;
        quantity: bigint;
        createdAt: bigint;
        itemType: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketplaceFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "monToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "offerService"
  ): TypedContractMethod<
    [serviceType: string, pricePerAction: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "purchaseItem"
  ): TypedContractMethod<
    [listingId: BigNumberish, quantity: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "purchaseService"
  ): TypedContractMethod<[serviceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "serviceCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "services"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, string] & {
        provider: string;
        pricePerAction: bigint;
        completedJobs: bigint;
        active: boolean;
        serviceType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setMarketplaceFee"
  ): TypedContractMethod<[newFeePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalInvested"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawInvestment"
  ): TypedContractMethod<[investmentId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentMade"
  ): TypedContractEvent<
    InvestmentMadeEvent.InputTuple,
    InvestmentMadeEvent.OutputTuple,
    InvestmentMadeEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentWithdrawn"
  ): TypedContractEvent<
    InvestmentWithdrawnEvent.InputTuple,
    InvestmentWithdrawnEvent.OutputTuple,
    InvestmentWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ItemListed"
  ): TypedContractEvent<
    ItemListedEvent.InputTuple,
    ItemListedEvent.OutputTuple,
    ItemListedEvent.OutputObject
  >;
  getEvent(
    key: "ItemPurchased"
  ): TypedContractEvent<
    ItemPurchasedEvent.InputTuple,
    ItemPurchasedEvent.OutputTuple,
    ItemPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "ListingCancelled"
  ): TypedContractEvent<
    ListingCancelledEvent.InputTuple,
    ListingCancelledEvent.OutputTuple,
    ListingCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketplaceFeeUpdated"
  ): TypedContractEvent<
    MarketplaceFeeUpdatedEvent.InputTuple,
    MarketplaceFeeUpdatedEvent.OutputTuple,
    MarketplaceFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProfitDistributed"
  ): TypedContractEvent<
    ProfitDistributedEvent.InputTuple,
    ProfitDistributedEvent.OutputTuple,
    ProfitDistributedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceCancelled"
  ): TypedContractEvent<
    ServiceCancelledEvent.InputTuple,
    ServiceCancelledEvent.OutputTuple,
    ServiceCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ServiceOffered"
  ): TypedContractEvent<
    ServiceOfferedEvent.InputTuple,
    ServiceOfferedEvent.OutputTuple,
    ServiceOfferedEvent.OutputObject
  >;
  getEvent(
    key: "ServicePurchased"
  ): TypedContractEvent<
    ServicePurchasedEvent.InputTuple,
    ServicePurchasedEvent.OutputTuple,
    ServicePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "InvestmentMade(uint256,address,address,uint256,uint256)": TypedContractEvent<
      InvestmentMadeEvent.InputTuple,
      InvestmentMadeEvent.OutputTuple,
      InvestmentMadeEvent.OutputObject
    >;
    InvestmentMade: TypedContractEvent<
      InvestmentMadeEvent.InputTuple,
      InvestmentMadeEvent.OutputTuple,
      InvestmentMadeEvent.OutputObject
    >;

    "InvestmentWithdrawn(uint256,address,uint256)": TypedContractEvent<
      InvestmentWithdrawnEvent.InputTuple,
      InvestmentWithdrawnEvent.OutputTuple,
      InvestmentWithdrawnEvent.OutputObject
    >;
    InvestmentWithdrawn: TypedContractEvent<
      InvestmentWithdrawnEvent.InputTuple,
      InvestmentWithdrawnEvent.OutputTuple,
      InvestmentWithdrawnEvent.OutputObject
    >;

    "ItemListed(uint256,address,string,uint256,uint256,uint256)": TypedContractEvent<
      ItemListedEvent.InputTuple,
      ItemListedEvent.OutputTuple,
      ItemListedEvent.OutputObject
    >;
    ItemListed: TypedContractEvent<
      ItemListedEvent.InputTuple,
      ItemListedEvent.OutputTuple,
      ItemListedEvent.OutputObject
    >;

    "ItemPurchased(uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;
    ItemPurchased: TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;

    "ListingCancelled(uint256,address)": TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;
    ListingCancelled: TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;

    "MarketplaceFeeUpdated(uint256,uint256)": TypedContractEvent<
      MarketplaceFeeUpdatedEvent.InputTuple,
      MarketplaceFeeUpdatedEvent.OutputTuple,
      MarketplaceFeeUpdatedEvent.OutputObject
    >;
    MarketplaceFeeUpdated: TypedContractEvent<
      MarketplaceFeeUpdatedEvent.InputTuple,
      MarketplaceFeeUpdatedEvent.OutputTuple,
      MarketplaceFeeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProfitDistributed(uint256,address,uint256)": TypedContractEvent<
      ProfitDistributedEvent.InputTuple,
      ProfitDistributedEvent.OutputTuple,
      ProfitDistributedEvent.OutputObject
    >;
    ProfitDistributed: TypedContractEvent<
      ProfitDistributedEvent.InputTuple,
      ProfitDistributedEvent.OutputTuple,
      ProfitDistributedEvent.OutputObject
    >;

    "ServiceCancelled(uint256,address)": TypedContractEvent<
      ServiceCancelledEvent.InputTuple,
      ServiceCancelledEvent.OutputTuple,
      ServiceCancelledEvent.OutputObject
    >;
    ServiceCancelled: TypedContractEvent<
      ServiceCancelledEvent.InputTuple,
      ServiceCancelledEvent.OutputTuple,
      ServiceCancelledEvent.OutputObject
    >;

    "ServiceOffered(uint256,address,string,uint256)": TypedContractEvent<
      ServiceOfferedEvent.InputTuple,
      ServiceOfferedEvent.OutputTuple,
      ServiceOfferedEvent.OutputObject
    >;
    ServiceOffered: TypedContractEvent<
      ServiceOfferedEvent.InputTuple,
      ServiceOfferedEvent.OutputTuple,
      ServiceOfferedEvent.OutputObject
    >;

    "ServicePurchased(uint256,address,address,uint256,uint256)": TypedContractEvent<
      ServicePurchasedEvent.InputTuple,
      ServicePurchasedEvent.OutputTuple,
      ServicePurchasedEvent.OutputObject
    >;
    ServicePurchased: TypedContractEvent<
      ServicePurchasedEvent.InputTuple,
      ServicePurchasedEvent.OutputTuple,
      ServicePurchasedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
