/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WorldBossInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BOSS_MAX_HEALTH"
      | "MAX_DAMAGE"
      | "MIN_DAMAGE"
      | "MIN_PARTICIPANTS"
      | "RESPAWN_COOLDOWN"
      | "attackBoss"
      | "bossCounter"
      | "claimReward"
      | "currentBoss"
      | "getBossStatus"
      | "getParticipantDamage"
      | "getParticipants"
      | "increasePrizePool"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "spawnBoss"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BossAttacked"
      | "BossDefeated"
      | "BossSpawned"
      | "OwnershipTransferred"
      | "Paused"
      | "PrizePoolIncreased"
      | "RewardClaimed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BOSS_MAX_HEALTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DAMAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DAMAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_PARTICIPANTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESPAWN_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attackBoss",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bossCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentBoss",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBossStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantDamage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipants",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "increasePrizePool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "spawnBoss", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BOSS_MAX_HEALTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_DAMAGE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_DAMAGE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PARTICIPANTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESPAWN_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attackBoss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bossCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentBoss",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBossStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantDamage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increasePrizePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "spawnBoss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace BossAttackedEvent {
  export type InputTuple = [
    bossId: BigNumberish,
    attacker: AddressLike,
    damage: BigNumberish,
    remainingHealth: BigNumberish
  ];
  export type OutputTuple = [
    bossId: bigint,
    attacker: string,
    damage: bigint,
    remainingHealth: bigint
  ];
  export interface OutputObject {
    bossId: bigint;
    attacker: string;
    damage: bigint;
    remainingHealth: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BossDefeatedEvent {
  export type InputTuple = [
    bossId: BigNumberish,
    defeatTime: BigNumberish,
    prizePool: BigNumberish,
    participantCount: BigNumberish
  ];
  export type OutputTuple = [
    bossId: bigint,
    defeatTime: bigint,
    prizePool: bigint,
    participantCount: bigint
  ];
  export interface OutputObject {
    bossId: bigint;
    defeatTime: bigint;
    prizePool: bigint;
    participantCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BossSpawnedEvent {
  export type InputTuple = [
    bossId: BigNumberish,
    maxHealth: BigNumberish,
    spawnTime: BigNumberish
  ];
  export type OutputTuple = [
    bossId: bigint,
    maxHealth: bigint,
    spawnTime: bigint
  ];
  export interface OutputObject {
    bossId: bigint;
    maxHealth: bigint;
    spawnTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizePoolIncreasedEvent {
  export type InputTuple = [
    bossId: BigNumberish,
    amount: BigNumberish,
    newTotal: BigNumberish
  ];
  export type OutputTuple = [bossId: bigint, amount: bigint, newTotal: bigint];
  export interface OutputObject {
    bossId: bigint;
    amount: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    bossId: BigNumberish,
    participant: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    bossId: bigint,
    participant: string,
    reward: bigint
  ];
  export interface OutputObject {
    bossId: bigint;
    participant: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorldBoss extends BaseContract {
  connect(runner?: ContractRunner | null): WorldBoss;
  waitForDeployment(): Promise<this>;

  interface: WorldBossInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BOSS_MAX_HEALTH: TypedContractMethod<[], [bigint], "view">;

  MAX_DAMAGE: TypedContractMethod<[], [bigint], "view">;

  MIN_DAMAGE: TypedContractMethod<[], [bigint], "view">;

  MIN_PARTICIPANTS: TypedContractMethod<[], [bigint], "view">;

  RESPAWN_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  attackBoss: TypedContractMethod<[damage: BigNumberish], [void], "nonpayable">;

  bossCounter: TypedContractMethod<[], [bigint], "view">;

  claimReward: TypedContractMethod<[], [void], "nonpayable">;

  currentBoss: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        currentHealth: bigint;
        maxHealth: bigint;
        prizePool: bigint;
        spawnTime: bigint;
        defeatTime: bigint;
        isActive: boolean;
        isDefeated: boolean;
      }
    ],
    "view"
  >;

  getBossStatus: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        health: bigint;
        maxHealth: bigint;
        prizePool: bigint;
        participantCount: bigint;
        isActive: boolean;
        isDefeated: boolean;
        spawnTime: bigint;
      }
    ],
    "view"
  >;

  getParticipantDamage: TypedContractMethod<
    [participant: AddressLike],
    [bigint],
    "view"
  >;

  getParticipants: TypedContractMethod<[], [string[]], "view">;

  increasePrizePool: TypedContractMethod<[], [void], "payable">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  spawnBoss: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BOSS_MAX_HEALTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DAMAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DAMAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PARTICIPANTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESPAWN_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "attackBoss"
  ): TypedContractMethod<[damage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bossCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentBoss"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        currentHealth: bigint;
        maxHealth: bigint;
        prizePool: bigint;
        spawnTime: bigint;
        defeatTime: bigint;
        isActive: boolean;
        isDefeated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBossStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        health: bigint;
        maxHealth: bigint;
        prizePool: bigint;
        participantCount: bigint;
        isActive: boolean;
        isDefeated: boolean;
        spawnTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipantDamage"
  ): TypedContractMethod<[participant: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getParticipants"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "increasePrizePool"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "spawnBoss"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BossAttacked"
  ): TypedContractEvent<
    BossAttackedEvent.InputTuple,
    BossAttackedEvent.OutputTuple,
    BossAttackedEvent.OutputObject
  >;
  getEvent(
    key: "BossDefeated"
  ): TypedContractEvent<
    BossDefeatedEvent.InputTuple,
    BossDefeatedEvent.OutputTuple,
    BossDefeatedEvent.OutputObject
  >;
  getEvent(
    key: "BossSpawned"
  ): TypedContractEvent<
    BossSpawnedEvent.InputTuple,
    BossSpawnedEvent.OutputTuple,
    BossSpawnedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PrizePoolIncreased"
  ): TypedContractEvent<
    PrizePoolIncreasedEvent.InputTuple,
    PrizePoolIncreasedEvent.OutputTuple,
    PrizePoolIncreasedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BossAttacked(uint256,address,uint256,uint256)": TypedContractEvent<
      BossAttackedEvent.InputTuple,
      BossAttackedEvent.OutputTuple,
      BossAttackedEvent.OutputObject
    >;
    BossAttacked: TypedContractEvent<
      BossAttackedEvent.InputTuple,
      BossAttackedEvent.OutputTuple,
      BossAttackedEvent.OutputObject
    >;

    "BossDefeated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      BossDefeatedEvent.InputTuple,
      BossDefeatedEvent.OutputTuple,
      BossDefeatedEvent.OutputObject
    >;
    BossDefeated: TypedContractEvent<
      BossDefeatedEvent.InputTuple,
      BossDefeatedEvent.OutputTuple,
      BossDefeatedEvent.OutputObject
    >;

    "BossSpawned(uint256,uint256,uint256)": TypedContractEvent<
      BossSpawnedEvent.InputTuple,
      BossSpawnedEvent.OutputTuple,
      BossSpawnedEvent.OutputObject
    >;
    BossSpawned: TypedContractEvent<
      BossSpawnedEvent.InputTuple,
      BossSpawnedEvent.OutputTuple,
      BossSpawnedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PrizePoolIncreased(uint256,uint256,uint256)": TypedContractEvent<
      PrizePoolIncreasedEvent.InputTuple,
      PrizePoolIncreasedEvent.OutputTuple,
      PrizePoolIncreasedEvent.OutputObject
    >;
    PrizePoolIncreased: TypedContractEvent<
      PrizePoolIncreasedEvent.InputTuple,
      PrizePoolIncreasedEvent.OutputTuple,
      PrizePoolIncreasedEvent.OutputObject
    >;

    "RewardClaimed(uint256,address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
