/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WorldTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ENTRY_FEE"
      | "MAX_REWARD_PER_ACTION"
      | "REWARD_COOLDOWN"
      | "agentToAgentTransfers"
      | "agents"
      | "distributeReward"
      | "enterWorld"
      | "getAgentStats"
      | "getWorldStats"
      | "isDistributor"
      | "monToken"
      | "owner"
      | "pause"
      | "paused"
      | "purchaseItem"
      | "renounceOwnership"
      | "setDistributor"
      | "totalAgents"
      | "totalFeesCollected"
      | "totalRewardsDistributed"
      | "transferOwnership"
      | "transferToAgent"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentEntered"
      | "AgentToAgentTransfer"
      | "DistributorUpdated"
      | "ItemPurchased"
      | "OwnershipTransferred"
      | "Paused"
      | "ReputationUpdated"
      | "RewardDistributed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(functionFragment: "ENTRY_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_REWARD_PER_ACTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentToAgentTransfers",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "distributeReward",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "enterWorld",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorldStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "monToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseItem",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDistributor",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRewardsDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferToAgent",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ENTRY_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REWARD_PER_ACTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentToAgentTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enterWorld", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorldStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "monToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRewardsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferToAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AgentEnteredEvent {
  export type InputTuple = [
    agent: AddressLike,
    entryFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    entryFee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agent: string;
    entryFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentToAgentTransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributorUpdatedEvent {
  export type InputTuple = [distributor: AddressLike, authorized: boolean];
  export type OutputTuple = [distributor: string, authorized: boolean];
  export interface OutputObject {
    distributor: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    seller: AddressLike,
    price: BigNumberish,
    itemType: string
  ];
  export type OutputTuple = [
    buyer: string,
    seller: string,
    price: bigint,
    itemType: string
  ];
  export interface OutputObject {
    buyer: string;
    seller: string;
    price: bigint;
    itemType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    oldScore: BigNumberish,
    newScore: BigNumberish
  ];
  export type OutputTuple = [agent: string, oldScore: bigint, newScore: bigint];
  export interface OutputObject {
    agent: string;
    oldScore: bigint;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    agent: AddressLike,
    amount: BigNumberish,
    reason: string,
    newBalance: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    amount: bigint,
    reason: string,
    newBalance: bigint
  ];
  export interface OutputObject {
    agent: string;
    amount: bigint;
    reason: string;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorldTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): WorldTreasury;
  waitForDeployment(): Promise<this>;

  interface: WorldTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ENTRY_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_REWARD_PER_ACTION: TypedContractMethod<[], [bigint], "view">;

  REWARD_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  agentToAgentTransfers: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {
        hasEntered: boolean;
        entryTime: bigint;
        totalEarned: bigint;
        totalSpent: bigint;
        actionCount: bigint;
        lastRewardTime: bigint;
        reputationScore: bigint;
      }
    ],
    "view"
  >;

  distributeReward: TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  enterWorld: TypedContractMethod<[], [void], "nonpayable">;

  getAgentStats: TypedContractMethod<
    [agent: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {
        hasEntered: boolean;
        entryTime: bigint;
        totalEarned: bigint;
        totalSpent: bigint;
        actionCount: bigint;
        currentBalance: bigint;
        reputationScore: bigint;
      }
    ],
    "view"
  >;

  getWorldStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalAgents: bigint;
        _totalFeesCollected: bigint;
        _totalRewardsDistributed: bigint;
        treasuryBalance: bigint;
      }
    ],
    "view"
  >;

  isDistributor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  monToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  purchaseItem: TypedContractMethod<
    [seller: AddressLike, price: BigNumberish, itemType: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDistributor: TypedContractMethod<
    [distributor: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  totalAgents: TypedContractMethod<[], [bigint], "view">;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  totalRewardsDistributed: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferToAgent: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ENTRY_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REWARD_PER_ACTION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentToAgentTransfers"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {
        hasEntered: boolean;
        entryTime: bigint;
        totalEarned: bigint;
        totalSpent: bigint;
        actionCount: bigint;
        lastRewardTime: bigint;
        reputationScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "distributeReward"
  ): TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterWorld"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgentStats"
  ): TypedContractMethod<
    [agent: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint] & {
        hasEntered: boolean;
        entryTime: bigint;
        totalEarned: bigint;
        totalSpent: bigint;
        actionCount: bigint;
        currentBalance: bigint;
        reputationScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorldStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalAgents: bigint;
        _totalFeesCollected: bigint;
        _totalRewardsDistributed: bigint;
        treasuryBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDistributor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "monToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "purchaseItem"
  ): TypedContractMethod<
    [seller: AddressLike, price: BigNumberish, itemType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDistributor"
  ): TypedContractMethod<
    [distributor: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRewardsDistributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferToAgent"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentEntered"
  ): TypedContractEvent<
    AgentEnteredEvent.InputTuple,
    AgentEnteredEvent.OutputTuple,
    AgentEnteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentToAgentTransfer"
  ): TypedContractEvent<
    AgentToAgentTransferEvent.InputTuple,
    AgentToAgentTransferEvent.OutputTuple,
    AgentToAgentTransferEvent.OutputObject
  >;
  getEvent(
    key: "DistributorUpdated"
  ): TypedContractEvent<
    DistributorUpdatedEvent.InputTuple,
    DistributorUpdatedEvent.OutputTuple,
    DistributorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ItemPurchased"
  ): TypedContractEvent<
    ItemPurchasedEvent.InputTuple,
    ItemPurchasedEvent.OutputTuple,
    ItemPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AgentEntered(address,uint256,uint256)": TypedContractEvent<
      AgentEnteredEvent.InputTuple,
      AgentEnteredEvent.OutputTuple,
      AgentEnteredEvent.OutputObject
    >;
    AgentEntered: TypedContractEvent<
      AgentEnteredEvent.InputTuple,
      AgentEnteredEvent.OutputTuple,
      AgentEnteredEvent.OutputObject
    >;

    "AgentToAgentTransfer(address,address,uint256,string)": TypedContractEvent<
      AgentToAgentTransferEvent.InputTuple,
      AgentToAgentTransferEvent.OutputTuple,
      AgentToAgentTransferEvent.OutputObject
    >;
    AgentToAgentTransfer: TypedContractEvent<
      AgentToAgentTransferEvent.InputTuple,
      AgentToAgentTransferEvent.OutputTuple,
      AgentToAgentTransferEvent.OutputObject
    >;

    "DistributorUpdated(address,bool)": TypedContractEvent<
      DistributorUpdatedEvent.InputTuple,
      DistributorUpdatedEvent.OutputTuple,
      DistributorUpdatedEvent.OutputObject
    >;
    DistributorUpdated: TypedContractEvent<
      DistributorUpdatedEvent.InputTuple,
      DistributorUpdatedEvent.OutputTuple,
      DistributorUpdatedEvent.OutputObject
    >;

    "ItemPurchased(address,address,uint256,string)": TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;
    ItemPurchased: TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "RewardDistributed(address,uint256,string,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
