import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import * as dotenv from 'dotenv';

// Load environment variables
dotenv.config();

async function resetWorld() {
    console.log('🔄  Starting World Reset Process...\n');

    // 1. Clear Local State
    const dataDir = path.join(__dirname, '../data');
    const stateFile = path.join(dataDir, 'world-state.json');

    console.log('🗑️   Clearing local world state...');
    if (fs.existsSync(stateFile)) {
        fs.unlinkSync(stateFile);
        console.log('    ✅ Deleted data/world-state.json');
    } else {
        console.log('    ✅ No existing state file found');
    }

    // 2. Redeploy Contracts
    console.log('\n⛓️   Redeploying Smart Contracts (this may take a minute)...');
    try {
        // Execute the deploy script defined in package.json
        execSync('npm run contracts:deploy', { stdio: 'inherit' });
        console.log('    ✅ Contracts deployed successfully');
    } catch (error) {
        console.error('    ❌ Failed to deploy contracts');
        process.exit(1);
    }

    // 3. Update .env with new addresses
    console.log('\n📝  Updating configuration...');

    // Path to deployment info generated by deploy.ts
    // deploy.ts runs in 'contracts' dir, so it outputs there
    const deploymentPath = path.join(__dirname, '../contracts/deployment-addresses.json');

    if (!fs.existsSync(deploymentPath)) {
        console.error(`    ❌ Could not find deployment file at: ${deploymentPath}`);
        process.exit(1);
    }

    const deploymentInfo = JSON.parse(fs.readFileSync(deploymentPath, 'utf-8'));
    const contracts = deploymentInfo.contracts;

    // Read current .env
    const envPath = path.join(__dirname, '../.env');
    let envContent = '';

    if (fs.existsSync(envPath)) {
        envContent = fs.readFileSync(envPath, 'utf-8');
    } else {
        console.log('    ⚠️  .env file not found, creating new one based on example...');
        // You might want to copy .env.example here if it exists, but for now we assume .env exists
    }

    // Helper to update or append env var
    const updateEnvVar = (key: string, value: string) => {
        const regex = new RegExp(`^${key}=.*`, 'm');
        if (regex.test(envContent)) {
            envContent = envContent.replace(regex, `${key}=${value}`);
        } else {
            envContent += `\n${key}=${value}`;
        }
        console.log(`    Updated ${key}`);
    };

    updateEnvVar('MON_TOKEN_ADDRESS', contracts.MONToken);
    updateEnvVar('WORLD_TREASURY_ADDRESS', contracts.WorldTreasury);
    updateEnvVar('AGENT_MARKETPLACE_ADDRESS', contracts.AgentMarketplace);

    fs.writeFileSync(envPath, envContent, 'utf-8');
    console.log('    ✅ .env file updated');

    console.log('\n✨  World Reset Complete!  ✨');
    console.log('You can now restart the server with: npm run start:blockchain');
}

resetWorld().catch(console.error);
